//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 11/12/2018 10:35:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace linQ_View
{

    [DatabaseAttribute(Name = "quanlythuvien")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class QUANLYTHUVIENDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(QUANLYTHUVIENDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);

        #endregion

        public QUANLYTHUVIENDataContext() :
        base(GetConnectionString("QUANLYTHUVIENDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public QUANLYTHUVIENDataContext(MappingSource mappingSource) :
        base(GetConnectionString("QUANLYTHUVIENDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public QUANLYTHUVIENDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public QUANLYTHUVIENDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public QUANLYTHUVIENDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public QUANLYTHUVIENDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<VIEWCT> VIEWCTs
        {
            get
            {
                return this.GetTable<VIEWCT>();
            }
        }

        public Devart.Data.Linq.Table<SACHVIEW> SACHVIEWs
        {
            get
            {
                return this.GetTable<SACHVIEW>();
            }
        }

        public Devart.Data.Linq.Table<PMCT> PMCTs
        {
            get
            {
                return this.GetTable<PMCT>();
            }
        }

        public Devart.Data.Linq.Table<VIEWPHAT> VIEWPHATs
        {
            get
            {
                return this.GetTable<VIEWPHAT>();
            }
        }
    }
}

namespace linQ_View
{

    /// <summary>
    /// VIEW
    /// </summary>
    [Table(Name = @"quanlythuvien.viewct")]
    public partial class VIEWCT
    {
        #pragma warning disable 0649

        private string _MAPHIEUMUON;

        private string _MASACH;

        private string _MANV;

        private string _MADG;

        private System.Nullable<System.DateTime> _NGAYMUON;

        private System.Nullable<System.DateTime> _NGAYDUKIENTRA;

        private System.Nullable<float> _PHICOC;

        private string _TINHTRANG;

        private System.Nullable<float> _Gia;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMAPHIEUMUONChanging(string value);
        partial void OnMAPHIEUMUONChanged();
        partial void OnMASACHChanging(string value);
        partial void OnMASACHChanged();
        partial void OnMANVChanging(string value);
        partial void OnMANVChanged();
        partial void OnMADGChanging(string value);
        partial void OnMADGChanged();
        partial void OnNGAYMUONChanging(System.Nullable<System.DateTime> value);
        partial void OnNGAYMUONChanged();
        partial void OnNGAYDUKIENTRAChanging(System.Nullable<System.DateTime> value);
        partial void OnNGAYDUKIENTRAChanged();
        partial void OnPHICOCChanging(System.Nullable<float> value);
        partial void OnPHICOCChanged();
        partial void OnTINHTRANGChanging(string value);
        partial void OnTINHTRANGChanged();
        partial void OnGiaChanging(System.Nullable<float> value);
        partial void OnGiaChanged();
        #endregion

        public VIEWCT()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MAPHIEUMUON in the schema.
        /// </summary>
        [Column(Storage = "_MAPHIEUMUON", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAPHIEUMUON
        {
            get
            {
                return this._MAPHIEUMUON;
            }
            set
            {
                if (this._MAPHIEUMUON != value)
                {
                    this._MAPHIEUMUON = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MASACH in the schema.
        /// </summary>
        [Column(Storage = "_MASACH", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MASACH
        {
            get
            {
                return this._MASACH;
            }
            set
            {
                if (this._MASACH != value)
                {
                    this._MASACH = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MANV in the schema.
        /// </summary>
        [Column(Storage = "_MANV", CanBeNull = false, DbType = "CHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MANV
        {
            get
            {
                return this._MANV;
            }
            set
            {
                if (this._MANV != value)
                {
                    this._MANV = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MADG in the schema.
        /// </summary>
        [Column(Storage = "_MADG", DbType = "CHAR(5) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MADG
        {
            get
            {
                return this._MADG;
            }
            set
            {
                if (this._MADG != value)
                {
                    this._MADG = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NGAYMUON in the schema.
        /// </summary>
        [Column(Storage = "_NGAYMUON", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> NGAYMUON
        {
            get
            {
                return this._NGAYMUON;
            }
            set
            {
                if (this._NGAYMUON != value)
                {
                    this._NGAYMUON = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NGAYDUKIENTRA in the schema.
        /// </summary>
        [Column(Storage = "_NGAYDUKIENTRA", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> NGAYDUKIENTRA
        {
            get
            {
                return this._NGAYDUKIENTRA;
            }
            set
            {
                if (this._NGAYDUKIENTRA != value)
                {
                    this._NGAYDUKIENTRA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PHICOC in the schema.
        /// </summary>
        [Column(Storage = "_PHICOC", DbType = "FLOAT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> PHICOC
        {
            get
            {
                return this._PHICOC;
            }
            set
            {
                if (this._PHICOC != value)
                {
                    this._PHICOC = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TINHTRANG in the schema.
        /// </summary>
        [Column(Storage = "_TINHTRANG", DbType = "VARCHAR(30) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TINHTRANG
        {
            get
            {
                return this._TINHTRANG;
            }
            set
            {
                if (this._TINHTRANG != value)
                {
                    this._TINHTRANG = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Gia in the schema.
        /// </summary>
        [Column(Storage = "_Gia", DbType = "FLOAT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> Gia
        {
            get
            {
                return this._Gia;
            }
            set
            {
                if (this._Gia != value)
                {
                    this._Gia = value;
                }
            }
        }
    }

    /// <summary>
    /// VIEW
    /// </summary>
    [Table(Name = @"quanlythuvien.sachview")]
    public partial class SACHVIEW
    {
        #pragma warning disable 0649

        private string _MASACH;

        private string _MATHELOAI;

        private string _MATACGIA;

        private string _MANXB;

        private string _MAVT;

        private string _TENSACH;

        private System.Nullable<int> _NAMXB;

        private string _HINHANHSACH;

        private string _MOTA;

        private string _KHOA;

        private System.Nullable<System.DateTime> _THANGNHAP;

        private System.Nullable<float> _GIA;

        private System.Nullable<int> _SOLUONG;

        private string _TENTACGIA;

        private string _TENNXB;

        private string _TENTHELOAI;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMASACHChanging(string value);
        partial void OnMASACHChanged();
        partial void OnMATHELOAIChanging(string value);
        partial void OnMATHELOAIChanged();
        partial void OnMATACGIAChanging(string value);
        partial void OnMATACGIAChanged();
        partial void OnMANXBChanging(string value);
        partial void OnMANXBChanged();
        partial void OnMAVTChanging(string value);
        partial void OnMAVTChanged();
        partial void OnTENSACHChanging(string value);
        partial void OnTENSACHChanged();
        partial void OnNAMXBChanging(System.Nullable<int> value);
        partial void OnNAMXBChanged();
        partial void OnHINHANHSACHChanging(string value);
        partial void OnHINHANHSACHChanged();
        partial void OnMOTAChanging(string value);
        partial void OnMOTAChanged();
        partial void OnKHOAChanging(string value);
        partial void OnKHOAChanged();
        partial void OnTHANGNHAPChanging(System.Nullable<System.DateTime> value);
        partial void OnTHANGNHAPChanged();
        partial void OnGIAChanging(System.Nullable<float> value);
        partial void OnGIAChanged();
        partial void OnSOLUONGChanging(System.Nullable<int> value);
        partial void OnSOLUONGChanged();
        partial void OnTENTACGIAChanging(string value);
        partial void OnTENTACGIAChanged();
        partial void OnTENNXBChanging(string value);
        partial void OnTENNXBChanged();
        partial void OnTENTHELOAIChanging(string value);
        partial void OnTENTHELOAIChanged();
        #endregion

        public SACHVIEW()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MASACH in the schema.
        /// </summary>
        [Column(Storage = "_MASACH", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MASACH
        {
            get
            {
                return this._MASACH;
            }
            set
            {
                if (this._MASACH != value)
                {
                    this._MASACH = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MATHELOAI in the schema.
        /// </summary>
        [Column(Storage = "_MATHELOAI", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MATHELOAI
        {
            get
            {
                return this._MATHELOAI;
            }
            set
            {
                if (this._MATHELOAI != value)
                {
                    this._MATHELOAI = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MATACGIA in the schema.
        /// </summary>
        [Column(Storage = "_MATACGIA", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MATACGIA
        {
            get
            {
                return this._MATACGIA;
            }
            set
            {
                if (this._MATACGIA != value)
                {
                    this._MATACGIA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MANXB in the schema.
        /// </summary>
        [Column(Storage = "_MANXB", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MANXB
        {
            get
            {
                return this._MANXB;
            }
            set
            {
                if (this._MANXB != value)
                {
                    this._MANXB = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MAVT in the schema.
        /// </summary>
        [Column(Storage = "_MAVT", DbType = "CHAR(5) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAVT
        {
            get
            {
                return this._MAVT;
            }
            set
            {
                if (this._MAVT != value)
                {
                    this._MAVT = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TENSACH in the schema.
        /// </summary>
        [Column(Storage = "_TENSACH", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TENSACH
        {
            get
            {
                return this._TENSACH;
            }
            set
            {
                if (this._TENSACH != value)
                {
                    this._TENSACH = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NAMXB in the schema.
        /// </summary>
        [Column(Storage = "_NAMXB", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> NAMXB
        {
            get
            {
                return this._NAMXB;
            }
            set
            {
                if (this._NAMXB != value)
                {
                    this._NAMXB = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for HINHANHSACH in the schema.
        /// </summary>
        [Column(Storage = "_HINHANHSACH", DbType = "VARCHAR(100) NULL", UpdateCheck = UpdateCheck.Never)]
        public string HINHANHSACH
        {
            get
            {
                return this._HINHANHSACH;
            }
            set
            {
                if (this._HINHANHSACH != value)
                {
                    this._HINHANHSACH = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MOTA in the schema.
        /// </summary>
        [Column(Storage = "_MOTA", DbType = "VARCHAR(1500) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MOTA
        {
            get
            {
                return this._MOTA;
            }
            set
            {
                if (this._MOTA != value)
                {
                    this._MOTA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KHOA in the schema.
        /// </summary>
        [Column(Storage = "_KHOA", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string KHOA
        {
            get
            {
                return this._KHOA;
            }
            set
            {
                if (this._KHOA != value)
                {
                    this._KHOA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for THANGNHAP in the schema.
        /// </summary>
        [Column(Storage = "_THANGNHAP", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> THANGNHAP
        {
            get
            {
                return this._THANGNHAP;
            }
            set
            {
                if (this._THANGNHAP != value)
                {
                    this._THANGNHAP = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for GIA in the schema.
        /// </summary>
        [Column(Storage = "_GIA", DbType = "FLOAT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> GIA
        {
            get
            {
                return this._GIA;
            }
            set
            {
                if (this._GIA != value)
                {
                    this._GIA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SOLUONG in the schema.
        /// </summary>
        [Column(Storage = "_SOLUONG", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> SOLUONG
        {
            get
            {
                return this._SOLUONG;
            }
            set
            {
                if (this._SOLUONG != value)
                {
                    this._SOLUONG = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TENTACGIA in the schema.
        /// </summary>
        [Column(Storage = "_TENTACGIA", DbType = "VARCHAR(30) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TENTACGIA
        {
            get
            {
                return this._TENTACGIA;
            }
            set
            {
                if (this._TENTACGIA != value)
                {
                    this._TENTACGIA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TENNXB in the schema.
        /// </summary>
        [Column(Storage = "_TENNXB", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TENNXB
        {
            get
            {
                return this._TENNXB;
            }
            set
            {
                if (this._TENNXB != value)
                {
                    this._TENNXB = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TENTHELOAI in the schema.
        /// </summary>
        [Column(Storage = "_TENTHELOAI", DbType = "VARCHAR(30) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TENTHELOAI
        {
            get
            {
                return this._TENTHELOAI;
            }
            set
            {
                if (this._TENTHELOAI != value)
                {
                    this._TENTHELOAI = value;
                }
            }
        }
    }

    /// <summary>
    /// VIEW
    /// </summary>
    [Table(Name = @"quanlythuvien.pmct")]
    public partial class PMCT
    {
        #pragma warning disable 0649

        private string _MAPHIEUMUON;

        private string _MASACH;

        private string _MANV;

        private string _MADG;

        private System.Nullable<System.DateTime> _NGAYMUON;

        private System.Nullable<System.DateTime> _NGAYDUKIENTRA;

        private System.Nullable<float> _PHICOC;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMAPHIEUMUONChanging(string value);
        partial void OnMAPHIEUMUONChanged();
        partial void OnMASACHChanging(string value);
        partial void OnMASACHChanged();
        partial void OnMANVChanging(string value);
        partial void OnMANVChanged();
        partial void OnMADGChanging(string value);
        partial void OnMADGChanged();
        partial void OnNGAYMUONChanging(System.Nullable<System.DateTime> value);
        partial void OnNGAYMUONChanged();
        partial void OnNGAYDUKIENTRAChanging(System.Nullable<System.DateTime> value);
        partial void OnNGAYDUKIENTRAChanged();
        partial void OnPHICOCChanging(System.Nullable<float> value);
        partial void OnPHICOCChanged();
        #endregion

        public PMCT()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MAPHIEUMUON in the schema.
        /// </summary>
        [Column(Storage = "_MAPHIEUMUON", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAPHIEUMUON
        {
            get
            {
                return this._MAPHIEUMUON;
            }
            set
            {
                if (this._MAPHIEUMUON != value)
                {
                    this._MAPHIEUMUON = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MASACH in the schema.
        /// </summary>
        [Column(Storage = "_MASACH", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MASACH
        {
            get
            {
                return this._MASACH;
            }
            set
            {
                if (this._MASACH != value)
                {
                    this._MASACH = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MANV in the schema.
        /// </summary>
        [Column(Storage = "_MANV", CanBeNull = false, DbType = "CHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MANV
        {
            get
            {
                return this._MANV;
            }
            set
            {
                if (this._MANV != value)
                {
                    this._MANV = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MADG in the schema.
        /// </summary>
        [Column(Storage = "_MADG", DbType = "CHAR(5) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MADG
        {
            get
            {
                return this._MADG;
            }
            set
            {
                if (this._MADG != value)
                {
                    this._MADG = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NGAYMUON in the schema.
        /// </summary>
        [Column(Storage = "_NGAYMUON", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> NGAYMUON
        {
            get
            {
                return this._NGAYMUON;
            }
            set
            {
                if (this._NGAYMUON != value)
                {
                    this._NGAYMUON = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NGAYDUKIENTRA in the schema.
        /// </summary>
        [Column(Storage = "_NGAYDUKIENTRA", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> NGAYDUKIENTRA
        {
            get
            {
                return this._NGAYDUKIENTRA;
            }
            set
            {
                if (this._NGAYDUKIENTRA != value)
                {
                    this._NGAYDUKIENTRA = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PHICOC in the schema.
        /// </summary>
        [Column(Storage = "_PHICOC", DbType = "FLOAT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> PHICOC
        {
            get
            {
                return this._PHICOC;
            }
            set
            {
                if (this._PHICOC != value)
                {
                    this._PHICOC = value;
                }
            }
        }
    }

    /// <summary>
    /// VIEW
    /// </summary>
    [Table(Name = @"quanlythuvien.viewphat")]
    public partial class VIEWPHAT
    {
        #pragma warning disable 0649

        private string _MAPHAT;

        private string _MADG;

        private System.Nullable<float> _TIENPHAT;

        private string _TENDIEUKHOAN;

        private string _GHICHU;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMAPHATChanging(string value);
        partial void OnMAPHATChanged();
        partial void OnMADGChanging(string value);
        partial void OnMADGChanged();
        partial void OnTIENPHATChanging(System.Nullable<float> value);
        partial void OnTIENPHATChanged();
        partial void OnTENDIEUKHOANChanging(string value);
        partial void OnTENDIEUKHOANChanged();
        partial void OnGHICHUChanging(string value);
        partial void OnGHICHUChanged();
        #endregion

        public VIEWPHAT()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MAPHAT in the schema.
        /// </summary>
        [Column(Storage = "_MAPHAT", CanBeNull = false, DbType = "CHAR(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAPHAT
        {
            get
            {
                return this._MAPHAT;
            }
            set
            {
                if (this._MAPHAT != value)
                {
                    this._MAPHAT = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MADG in the schema.
        /// </summary>
        [Column(Storage = "_MADG", DbType = "CHAR(5) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MADG
        {
            get
            {
                return this._MADG;
            }
            set
            {
                if (this._MADG != value)
                {
                    this._MADG = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TIENPHAT in the schema.
        /// </summary>
        [Column(Storage = "_TIENPHAT", DbType = "FLOAT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<float> TIENPHAT
        {
            get
            {
                return this._TIENPHAT;
            }
            set
            {
                if (this._TIENPHAT != value)
                {
                    this._TIENPHAT = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TENDIEUKHOAN in the schema.
        /// </summary>
        [Column(Storage = "_TENDIEUKHOAN", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string TENDIEUKHOAN
        {
            get
            {
                return this._TENDIEUKHOAN;
            }
            set
            {
                if (this._TENDIEUKHOAN != value)
                {
                    this._TENDIEUKHOAN = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for GHICHU in the schema.
        /// </summary>
        [Column(Storage = "_GHICHU", DbType = "VARCHAR(500) NULL", UpdateCheck = UpdateCheck.Never)]
        public string GHICHU
        {
            get
            {
                return this._GHICHU;
            }
            set
            {
                if (this._GHICHU != value)
                {
                    this._GHICHU = value;
                }
            }
        }
    }

}
