using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QuanLyThuVien
{
    public partial class fThongKeDoanhThu : DevExpress.XtraEditors.XtraForm
    {
        public fThongKeDoanhThu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
            // This line of code is generated by Data Source Configuration Wizard
            //viewDoanhThusBindingSource.DataSource = new linQ.DataTVDataContext().viewDoanhThus;
            // This line of code is generated by Data Source Configuration Wizard
            //chartControl1.DataSource = new linQ.DataTVDataContext().viewDoanhThus;
            
        }
    }
}
